name: testss
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: test
        run: 'echo "run"'
  deploy:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          env: ['dev','prod']
    environment: ${{ matrix.env }}
    steps:
      - name: test
        run: 'echo "run"'
